//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOHIEM
    {
        public int MABH { get; set; }
        public int MANV { get; set; }
        public string LOAIBH { get; set; }
        public string SOBH { get; set; }
        public string BENHVIEN { get; set; }
        public System.DateTime NGAYCAP { get; set; }
        public System.DateTime NGAY_HETHAN { get; set; }
        public string TINHTRANG { get; set; }
    
        public virtual NHANSU NHANSU { get; set; }
    }
}
