//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETNHAPKHO
    {
        public int ID { get; set; }
        public int MAPHIEUNHAP { get; set; }
        public int MASP { get; set; }
        public int SOLUONGNHAP { get; set; }
        public long DONGIA { get; set; }
        public Nullable<System.DateTime> NGAYHETHAN { get; set; }
    
        public virtual NHAPKHO NHAPKHO { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
