//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public int ID { get; set; }
        public int MAHD { get; set; }
        public int MASP { get; set; }
        public int SOLUONG { get; set; }
        public long DONGIA { get; set; }
        public Nullable<double> CHIETKHAU { get; set; }
        public double VAT { get; set; }
        public string GHICHU { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
