//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETXUATKHO
    {
        public int ID { get; set; }
        public int MAPHIEUXUAT { get; set; }
        public int MASP { get; set; }
        public int SOLUONGXUAT { get; set; }
        public string GHICHU { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual XUATKHO XUATKHO { get; set; }
    }
}
