//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUONG
    {
        public int MALUONG { get; set; }
        public int MANV { get; set; }
        public int THANG { get; set; }
        public int NAM { get; set; }
        public double LUONGCB { get; set; }
        public double TONGTC { get; set; }
        public double TONGPC { get; set; }
        public double THUCLINH { get; set; }
    
        public virtual NHANSU NHANSU { get; set; }
    }
}
