//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG
    {
        public string TEN_ND { get; set; }
        public string MATKHAU { get; set; }
        public string MAVAITRO { get; set; }
    
        public virtual VAITRO VAITRO { get; set; }
    }
}
