//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAPKHO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHAPKHO()
        {
            this.CHITIETNHAPKHOes = new HashSet<CHITIETNHAPKHO>();
        }
    
        public int MAPHIEUNHAP { get; set; }
        public System.DateTime NGAYNHAP { get; set; }
        public int MANCC { get; set; }
        public int MAKHO { get; set; }
        public string GHICHU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETNHAPKHO> CHITIETNHAPKHOes { get; set; }
        public virtual KHOHANG KHOHANG { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
