//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANQUYEN
    {
        public string MAVAITRO { get; set; }
        public int MAQUYEN { get; set; }
        public string HANHDONG { get; set; }
    
        public virtual QUYEN QUYEN { get; set; }
        public virtual VAITRO VAITRO { get; set; }
    }
}
