//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETNHAPKHOes = new HashSet<CHITIETNHAPKHO>();
            this.CHITIETXUATKHOes = new HashSet<CHITIETXUATKHO>();
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
            this.TONKHOes = new HashSet<TONKHO>();
        }
    
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public string MOTA { get; set; }
        public int MANCC { get; set; }
        public int MAMATHANG { get; set; }
        public long DONGIA { get; set; }
        public int SOLUONGTON { get; set; }
        public System.DateTime NGAYNHAP { get; set; }
        public string TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETNHAPKHO> CHITIETNHAPKHOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETXUATKHO> CHITIETXUATKHOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual PHANLOAIMATHANG PHANLOAIMATHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TONKHO> TONKHOes { get; set; }
    }
}
