//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TANGCA
    {
        public int MA_TANGCA { get; set; }
        public System.DateTime NGAY { get; set; }
        public int SOGIO { get; set; }
        public int MANV { get; set; }
        public int MA_LOAICA { get; set; }
    
        public virtual LOAICA LOAICA { get; set; }
        public virtual NHANSU NHANSU { get; set; }
    }
}
