//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class THU
    {
        public int MATHU { get; set; }
        public int MANV { get; set; }
        public System.DateTime NGAYTHU { get; set; }
        public string NOIDUNG { get; set; }
        public double SOTIEN { get; set; }
        public string NGUOITHU { get; set; }
        public string GHICHU { get; set; }
    
        public virtual NHANSU NHANSU { get; set; }
    }
}
