//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class XUATKHO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XUATKHO()
        {
            this.CHITIETXUATKHOes = new HashSet<CHITIETXUATKHO>();
        }
    
        public int MAPHIEUXUAT { get; set; }
        public int MAKHO { get; set; }
        public string NGUOIXUAT { get; set; }
        public Nullable<System.DateTime> NGAYXUAT { get; set; }
        public string LYDOXUAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETXUATKHO> CHITIETXUATKHOes { get; set; }
        public virtual KHOHANG KHOHANG { get; set; }
    }
}
